const data = {
  product: [
    {
      _id: '1',
      name: 'Alexia top',
      slug: 'pole-dance-alexia-top',
      catagory: 'top',
      image: '/images/img1.jpg',
      price: 25,
      countInStock: 0,
      brand: 'LAN.',
      rating: 2.5,
      numReviews: 10,
      description: 'stylish pole dance top',
    },
    {
      _id: '2',
      name: 'Lace top',
      slug: 'pole-dance-lace-top',
      catagory: 'top',
      image: '/images/img2.jpg',
      price: 27,
      countInStock: 3,
      brand: 'LAN.',
      rating: 0.5,
      numReviews: 10,
      description: 'lace pole dance top',
    },
    {
      _id: '3',
      name: 'Black swan top',
      slug: 'pole-dance-black-swan-top',
      catagory: 'top',
      image: '/images/img3.jpg',
      price: 45,
      countInStock: 5,
      brand: 'LAN.',
      rating: 0,
      numReviews: 10,
      description: 'black pole dance top',
    },
    {
      _id: '4',
      name: 'Lavendar top',
      slug: 'pole-dance-lavendar-top',
      catagory: 'top',
      image: '/images/img4.jpg',
      price: 27,
      countInStock: 1,
      brand: 'LAN.',
      rating: 5,
      numReviews: 10,
      description: 'lavendar pole dance top',
    },
  ],
};
export default data;
